In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('mentalhealth_dataset.csv')
df.head()

,Timestamp,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
0,13/7/2020,Female,24,Biotechnology,Year 3,2.38,1,0,0,0,5,0,4,5,8,2
1,13/7/2020,Female,18,Biotechnology,Year 3,4.00,0,1,0,0,0,0,4,4,13,5
2,13/7/2020,Female,25,Biotechnology,Year 3,3.68,0,0,1,0,3,0,1,2,13,1
3,13/7/2020,Female,18,Engineering,year 4,4.00,0,0,0,0,3,0,5,1,19,2
4,13/7/2020,Female,20,Engineering,year 4,2.00,1,1,0,0,0,0,2,4,3,2

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timestamp                   1000 non-null   str
 1   Gender                      1000 non-null   str
 2   Age                         1000 non-null   int64
 3   Course                      1000 non-null   str
 4   YearOfStudy                 1000 non-null   str
 5   CGPA                        1000 non-null   float64
 6   Depression                  1000 non-null   int64
 7   Anxiety                     1000 non-null   int64
 8   PanicAttack                 1000 non-null   int64
 9   SpecialistTreatment         1000 non-null   int64
 10  SymptomFrequency_Last7Days  1000 non-null   int64
 11  HasMentalHealthSupport      1000 non-null   int64
 12  SleepQuality                1000 non-null   int64
 13  StudyStressLevel            1000 non-null   int64
 14  StudyHoursPerWeek           1000 non-null   int64
 15  AcademicEngagement          1000 non-null   int64
dtypes: float64(1), int64(11), str(4)
memory usage: 125.1 KB

In [25]:
#standardizing string values
df_clean = df.copy()
df.YearOfStudy.unique()

<StringArray>
['Year 3', 'year 4', 'Year 2', 'year 2', 'year 1', 'Year 1', 'year 3']
Length: 7, dtype: str

In [30]:

string_cols = ['Gender', 'Course','YearOfStudy']
for col in string_cols:
    df_clean[col] = df[col].str.lower().str.strip()
print(f"Standardized Years: {df_clean['YearOfStudy'].unique()}")
print(f"Standardized Majors: {df_clean['Course'].unique()}")

Standardized Years: <StringArray>
['year 3', 'year 4', 'year 2', 'year 1']
Length: 4, dtype: str
Standardized Majors: <StringArray>
[          'biotechnology',             'engineering',
           'communication',         'diploma nursing',
        'pendidikan islam',             'radiography',
              'psychology',              'fiqh fatwa',
                     'bit',            'diploma tesl',
                     'koe',                    'benl',
                    'fiqh',       'islamic education',
                     'bcs',                 'nursing',
      'biomedical science',                    'laws',
            'mathemathics',         'human resources',
                   'irkhs',                   'kenms',
              'accounting',                     'enm',
          'marine science',         'banking studies',
 'business administration',                     'law',
                  'kirkhs',               'usuluddin',
                   'taasl',                  'engine',
                     'cts',                   'engin',
                   'econs',                    'mhsc',
                  'malcom',                     'kop',
          'human sciences',                     'ala',
                      'it']
Length: 41, dtype: str

In [32]:
df_clean.head()

,Timestamp,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
0,13/7/2020,female,24,biotechnology,year 3,2.38,1,0,0,0,5,0,4,5,8,2
1,13/7/2020,female,18,biotechnology,year 3,4.00,0,1,0,0,0,0,4,4,13,5
2,13/7/2020,female,25,biotechnology,year 3,3.68,0,0,1,0,3,0,1,2,13,1
3,13/7/2020,female,18,engineering,year 4,4.00,0,0,0,0,3,0,5,1,19,2
4,13/7/2020,female,20,engineering,year 4,2.00,1,1,0,0,0,0,2,4,3,2

In [41]:
#Majors corrections and translations
course_cleanup = {
    'bit': 'it',
    'koe': 'engineering',
    'bcs': 'computer science',
    'irkhs': 'ahas kirkhs',
    'kirkhs': 'ahas kirkhs',
    'cts': 'computer science',
    'econs': 'economics',
    'malcom': 'communication',
    'diploma nursing': 'nursing',
    'benl': 'english learning and literature',
    'diploma tesl': 'teaching english as second language',
    'laws': 'law',
    'kenms': 'economics',
    'enm': 'economics',
    'engine': 'engineering',
    'engin': 'engineering',
    'mhsc': 'health science',
    'kop': 'pharmacy',
    'ala': 'arabic language and literature',
    'human sciences': 'human science',
    'taasl': 'teaching arabic as second language',
    'mathemathics': 'mathematics'
}
df_clean['Course'] = df_clean['Course'].replace(course_cleanup)
df_clean['Course'].value_counts()

Course
engineering                            274
computer science                       192
it                                     109
biomedical science                      33
law                                     32
ahas kirkhs                             32
pendidikan islam                        29
psychology                              29
communication                           25
english learning and literature         24
economics                               24
nursing                                 21
islamic education                       14
business administration                 14
human science                           13
marine science                          12
teaching english as second language     11
fiqh                                    11
accounting                              11
usuluddin                               11
radiography                              9
fiqh fatwa                               9
mathematics                              9
human resources                          9
teaching arabic as second language       9
biotechnology                            8
pharmacy                                 8
banking studies                          6
health science                           6
arabic language and literature           6
Name: count, dtype: int64

In [42]:
#making columns to ensure distribution for variance
def categorize_major(course):
    stem = ['engineering', 'computer science', 'it', 'biomedical science', 'nursing', 'marine science', 'mathematics', 'biotechnology', 'pharmacy', 'health science', 'radiography']
    humanities = ['psychology', 'communication', 'english learning and literature', 'human science', 'teaching english as second language', 'human resources', 'teaching arabic as second language', 'arabic language and literature']
    law_bus_econ = ['law', 'economics', 'business administration', 'accounting', 'banking studies']
    religion = ['ahas kirkhs', 'pendidikan islam', 'islamic education', 'fiqh', 'usuluddin', 'fiqh fatwa']

    if course in stem: return 'STEM'
    if course in humanities: return 'Humanities'
    if course in law_bus_econ: return 'Law/Bus/Econ'
    if course in religion: return 'Religious Studies'
    return 'Other'

df_clean['Major_Category'] = df_clean['Course'].apply(categorize_major)
print(df_clean['Major_Category'].value_counts())

Major_Category
STEM                 681
Humanities           126
Religious Studies    106
Law/Bus/Econ          87
Name: count, dtype: int64